#!/usr/bin/env python3
"""
Quick demo of Google Gemini provider integration
"""

import os
import sys
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent
sys.path.insert(0, str(project_root))

# Add runtime directory for direct imports
runtime_dir = project_root / "agency_os" / "00_system" / "runtime"
sys.path.insert(0, str(runtime_dir))

print("🔥 GOOGLE GEMINI PROVIDER - LIVE INTEGRATION DEMO")
print("=" * 70)
print()

# Demo 1: Show provider detection works
print("Demo 1: Auto-detection with GOOGLE_API_KEY")
print("-" * 70)

os.environ["GOOGLE_API_KEY"] = "demo-key-12345"

from providers.factory import _detect_provider, create_provider

detected = _detect_provider()
print(f"✅ Detected provider: {detected}")
print(f"   (GOOGLE_API_KEY takes highest priority)")
print()

# Demo 2: Show provider creation
print("Demo 2: Provider creation and metadata")
print("-" * 70)

provider = create_provider(provider_name="google", api_key="demo-key")
print(f"✅ Provider type: {provider.__class__.__name__}")
print(f"✅ Provider name: {provider.get_provider_name()}")

if hasattr(provider, 'get_available_models'):
    models = provider.get_available_models()
    print(f"✅ Available models: {models}")
print()

# Demo 3: Show pricing
print("Demo 3: Pricing information")
print("-" * 70)

from providers.google import GoogleProvider

pricing = GoogleProvider.PRICING
for model, costs in pricing.items():
    print(f"   {model}:")
    print(f"      Input:  ${costs['input']}/MTok")
    print(f"      Output: ${costs['output']}/MTok")
print()

# Demo 4: Show cost calculation
print("Demo 4: Cost calculation example")
print("-" * 70)

# Example: 1000 input tokens, 500 output tokens on gemini-1.5-flash
if provider.__class__.__name__ != "NoOpProvider":
    test_cost = provider.calculate_cost(
        input_tokens=1000,
        output_tokens=500,
        model="gemini-1.5-flash"
    )
    print(f"   Example request (gemini-1.5-flash):")
    print(f"      1,000 input tokens  = ${(1000/1_000_000) * 0.075:.6f}")
    print(f"      500 output tokens   = ${(500/1_000_000) * 0.30:.6f}")
    print(f"      Total cost          = ${test_cost:.6f}")
else:
    print("   ⚠️  NoOpProvider - cost calculation would be $0.00")
print()

# Demo 5: Show LLMClient integration
print("Demo 5: LLMClient integration")
print("-" * 70)

from llm_client import LLMClient

client = LLMClient(budget_limit=1.0)
print(f"✅ Client initialized")
print(f"   Mode: {client.mode}")
print(f"   Provider: {client.provider.get_provider_name()}")
print(f"   Budget: ${client.budget_limit}")
print()

# Clean up
del os.environ["GOOGLE_API_KEY"]

print("=" * 70)
print("✅ GOOGLE GEMINI PROVIDER INTEGRATION: VERIFIED")
print("=" * 70)
print()
print("🚀 READY TO TEST WITH REAL API KEY")
print()
print("To test with real Google Gemini API:")
print()
print("  1. Get API key from: https://makersuite.google.com/app/apikey")
print()
print("  2. Set environment variable:")
print("     export GOOGLE_API_KEY='your-actual-key-here'")
print()
print("  3. Enable live fire:")
print("     export VIBE_LIVE_FIRE=true")
print()
print("  4. Run proof of intelligence:")
print("     uv run python scripts/prove_intelligence.py")
print()
print("Expected output:")
print("  ✅ Provider: GOOGLE - LIVE FIRE ARMED")
print("  ✅ Real code generated by Gemini 1.5 Flash")
print("  ✅ Actual cost tracked (very low: ~$0.0001)")
print()
